name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
        
    - name: dependences
      run: |
        sudo apt-get update
        sudo apt-get install yasm gcc automake autoconf libtool make
        
    - name: compile FFmpeg
      run: |
        sudo git clone https://github.com/FFmpeg/FFmpeg.git
        cd FFmpeg
        sudo ./configure --prefix=$FFMPEG_HOME --enable-static
        sudo make -j6
        sudo make install

    - name: Build-liunx_amd64
      run: go build -o GodCloud_liunx_amd64 

    - name: Upload binary files (liunx_amd64)
      uses: actions/upload-artifact@v2
      with:
        name: Build-liunx_amd64
        path: GodCloud_liunx_amd64
