name: Go

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:

  build-arm64:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-18.04,ubuntu-16.04]

    steps:
    - uses: actions/checkout@v2
        
    - name: dependences
      run: |
        sudo apt-get update
        sudo apt-get install yasm gcc automake autoconf libtool make wget
        sudo apt-get -y install gcc-aarch64-linux-gnu libc6-dev-arm64-cross
        
        
    - name: compile FFmpeg
      run: |
        sudo wget https://github.com/FFmpeg/FFmpeg/archive/n4.3.1.tar.gz
        tar -xzvf n4.3.1.tar.gz
        cd FFmpeg-n4.3.1
        sudo ./configure --prefix=$FFMPEG_HOME --enable-cross-compile --target-os=linux --cross-prefix=aarch64-linux-gnu- --cc=aarch64-linux-gnu-gcc --enable-static --arch=aarch64
        sudo make -j4
        cd ..
        tar -zcvf ffmpeg-arm64.tar.gz FFmpeg-n4.3.1
        
    - name: Upload binary files (linux_arm64)
      uses: actions/upload-artifact@v2
      with:
        name: Build-windows_amd64
        path: ffmpeg-arm64.tar.gz
           
  build2:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-18.04,ubuntu-16.04]
    steps:
    - uses: actions/checkout@v2
        
    - name: dependences
      run: |
        sudo apt-get update
        sudo apt-get install yasm gcc automake autoconf libtool make wget
        sudo apt install mingw-w64
                
    - name: compile FFmpeg
      run: |
        sudo wget https://github.com/FFmpeg/FFmpeg/archive/n4.3.1.tar.gz
        tar -xzvf n4.3.1.tar.gz
        cd FFmpeg-n4.3.1
        sudo ./configure --prefix=$FFMPEG_HOME --enable-cross-compile --target-os=win64 --cross-prefix=x86_64-w64-mingw32- --cc=x86_64-w64-mingw32-gcc --enable-static --arch=x86_64
        sudo make -j4
        cd ..
        tar -zcvf ffmpeg-windows.tar.gz FFmpeg-n4.3.1
        
    - name: Upload binary files (windows_amd64)
      uses: actions/upload-artifact@v2
      with:
        name: Build-windows_amd64
        path: ffmpeg-windows.tar.gz
    
  build3:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-18.04,ubuntu-16.04]

    steps:
    - uses: actions/checkout@v2
        
    - name: dependences
      run: |
        sudo apt-get update
        sudo apt-get install yasm gcc automake autoconf libtool make wget      
        
    - name: compile FFmpeg
      run: |
        sudo wget https://github.com/FFmpeg/FFmpeg/archive/n4.3.1.tar.gz
        tar -xzvf n4.3.1.tar.gz
        cd FFmpeg-n4.3.1
        sudo ./configure --prefix=$FFMPEG_HOME --target-os=linux --enable-static --arch=x86_64
        sudo make -j4
        cd ..
        tar -zcvf ffmpeg-linux-amd64.tar.gz FFmpeg-n4.3.1
        
    - name: Upload binary files (linux_amd64)
      uses: actions/upload-artifact@v2
      with:
        name: Build-linux_amd64
        path: ffmpeg-linux-amd64.tar.gz
  
