name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build-amd64
      run: go build -v ./... -o GodCloud_linux_amd64
    
    - name: Build-arm
      run: CGO_ENABLED=0 GOOS=linux GOARCH=arm go build -v ./... -o GodCloud_liunx_arm
    
    - name: Build-arm64
      run: CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -v ./... -o GodCloud_liunx_arm64
    
    - name: Build-arm32
      run: CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -v ./... -o GodCloud_windows_amd64
      
    - name: Upload binary files (windows_amd64)
      uses: actions/upload-artifact@v2
      with:
        name: Build-amd64
        path: GodCloud_windows_amd64

    - name: Upload binary files (linux_amd64)
      uses: actions/upload-artifact@v2
      with:
        name: Build-amd64
        path: GodCloud_linux_amd64

    - name: Upload binary files (linux_arm)
      uses: actions/upload-artifact@v2
      with:
        name: Build-arm
        path: GodCloud_linux_arm

    - name: Upload binary files (linux_arm64)
      uses: actions/upload-artifact@v2
      with:
        name: Build-amd64
        path: GodCloud_linux_arm64
