name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build-liunx_amd64
      run: |
        CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -o GodCloud_liunx_amd64

    - name: Build-liunx_arm64
      run: |
        CGO_ENABLED=1 GOOS=linux GOARCH=arm64 go build -o GodCloud_liunx_arm64
        
    - name: Build-liunx_arm
      run: |
        CGO_ENABLED=1 GOOS=linux GOARCH=arm go build -o GodCloud_liunx_arm    

    - name: Build-windows_amd64
      run: |
        CGO_ENABLED=1 GOOS=windows GOARCH=amd64 go build -o GodCloud_windows_amd64.exe
        
    - name: Upload binary files (liunx_amd64)
      uses: actions/upload-artifact@v2
      with:
        name: Build-liunx_amd64
        path: GodCloud_liunx_amd64

    - name: Upload binary files (liunx_arm64)
      uses: actions/upload-artifact@v2
      with:
        name: Build-liunx_arm64
        path: GodCloud_liunx_arm64
        
    - name: Upload binary files (liunx_arm)
      uses: actions/upload-artifact@v2
      with:
        name: Build-liunx_arm
        path: GodCloud_liunx_arm

    - name: Upload binary files (windows_amd64)
      uses: actions/upload-artifact@v2
      with:
        name: Build-windows_amd64
        path: GodCloud_windows_amd64.exe
